maximilianc88/Project-Planner-Application

.eslintignore
config/config.json
models/index.js
models/projects.js
models/tasks.js
package-lock.json
package.json
schema.sql

add sequelize, define Projects, define Tasks

---

.eslintignore
package.json
server.js

Created folder for public JS folder to house JS files for each page

Fleshed out public sub folder JS

---

models/tasks.js
routes/tasks-routes.js

Created tasks api routes for get all from specific project, get one b…y id, create one, delete one, and update body of one based on id

Tasks API routes

---

models/teams.js
models/users.js

add users model.
User.belongsTo(models.Team, {
as: `team_id`
});

add users model

---

models/projects.js
models/tasks.js
models/teams.js
models/users.js
public/js/viewTask.js

add association (relationship) to models.

update models relationship

---

routes/user-api.routes.js

User api routes for get, create, update, and destroy completed.

User api routes

---

models/projects.js
models/status.js
models/tasks.js
models/teams.js
models/users.js
schema.sql

add timestamp to models
createdAt: create_date
updatedAt: update_date
to models:
Project
Task
User
Team

add create_date, update_date to all relevant models

---

routes/status-api-routes.js

I think we will only need a get all statement. We won't want users to get a singular status from the status model (getting the status from projects or tasks will be done through the specific project or task which was assigned a status), nor updating the status model ( they will update a project or task status by the values defined in the status model), nor deleting any values from the status model. I think...

Added status get all statement.

---

projectsSeed.sql

Created a seed file for the projects table.

created seed file for projects table

---

public/js/dev.js
routes/dev-routes.js

add navigation routes to render pages

---

config/config.json
projectsSeed.sql
seeds.sql

I think this seeds.sql file should be good to go!

updated seeds.sql file

---

routes/dev-routes.js
routes/projects-routes.js
views/dashboard.handlebars
views/layouts/main.handlebars

connect dashboard.js to dashboard.handlebars

connect dashboard.js to dashboard.handlebars

---

routes/dev-routes.js
server.js

add all routes to js files to server
add all api routes to server
turn force update to false for sequelize

Add js routes

---

models/projects.js
models/status.js
models/tasks.js
models/teams.js
models/users.js
seeds.sql
server.js

fix associates

---

schema.sql
seed.js
server.js

add seed js

---

schema.sql
seed.js

add more seed data permutation.

add more seed

---

routes/users-api-routes.js

User get all and get one specific user functioning with new db archit…ecture

User get api routes updated

---

routes/projects-routes.js

Search specific project api route issue resolved

Fixed search specific project to reflect db architecture change

---

routes/projects-routes.js

When searching for a specific project the associated team and tasks will be returned in the response.

Added include model db.Team and model db.Task

---

public/js/newProject.js
views/newProject.handlebars

add redirect from cancel button in newProject

cancel button redirect in newProject

---

routes/users-api-routes.js

Searching for a specific user will now return all unique user data, associated team, and personal tasks

Adjusted specific user search to return user team and user tasks

---

routes/dev-routes.js
views/layouts/main.handlebars

update navbar items (home, dashboard, add new, setting)
update routes to add new project, add new task, dashboard.

update navbar 

---

public/js/newTask.js
seed.js
views/newProject.handlebars
views/newTask.handlebars

add newTask handlebars elements
add newTask js
add api request, find all projects.
add list of projects to select project option list
get user selected project_id and assigned team_id

Add new task

---

public/js/newTask.js
seed.js

get a list of users with respect to selected project
append the list of user options to drop down list
capture user_id from selected user for the task

New task users option list update

---

public/js/newProject.js
views/newProject.handlebars

New project now posting to database and redirects for add task as well as return home

New project post and redirect functionality

---

public/js/newTask.js

resolve error in console when receive null for user list

resolve error when return null

---

public/js/stats.js
routes/dev-routes.js
views/layouts/main.handlebars
views/stats.handlebars

Charts are now rendering for team project tasks status as well as user tasks status. The data is fake... for now

Adding stats page

---

public/js/stats.js

Fixed magic number linter error

---

routes/dev-routes.js
server.js
views/dashboard.handlebars
views/layouts/main.handlebars
views/newProject.handlebars
views/newTask.handlebars

update script src in handlebars files correctly

update script src to public

---

public/js/dashboard.js
public/js/viewProject.js
routes/dev-routes.js
seed.js
server.js
views/dashboard.handlebars
views/layouts/main.handlebars
views/project.handlebars
views/stats.handlebars

fixed static directory issue
now every path and source static directory. 
example: localhost:3000/ or localhost:3000/project/1 can all source same static directory
set up a way to render handlebar file for existing project, will pass data to handlebars.

Fix route render

---

routes/dev-routes.js
views/layouts/main.handlebars
views/project.handlebars

make /project/:id api call
make data call
render project page with data for requested project id

Render project handlebars

---

models/projects.js
package.json
public/js/project.js
public/js/viewProject.js
routes/navigation-routes.js
seed.js
server.js
views/project.handlebars

add handlebars element to project/:id page
request project data, team name, task data, assignee name data to project/:id page
bring data in to project.handlebars (no js)

Project handlebars

---

public/js/viewTask.js
routes/navigation-routes.js
views/layouts/main.handlebars
views/task.handlebars

The view tasks page works almost exactly like the view projects page. I already have an api call that works for getting the available status updates and displays them in a drop down menu. Note the submit button does not work yet for making a post api call to the update table yet.

Created the view tasks page (built similar to view projects)

---

public/js/dashboard.js

Updated hyperlinks for tasks/projects on dashboard page to route to the related tasks/projects detail pages.

Updated hyperlinks from dashboard for projects and tasks

---

public/js/stats.js
routes/navigation-routes.js

Charts are reflective of all project task data from database

Stats chart

---

public/js/newTask.js
test/newTask.test.js

added additional tests for newTask functions

New task tests

---

public/js/viewTask.js
views/task.handlebars

Put request is working for view task page

---

public/js/viewTask.js

Page reloads with updated status for task, immediately after button click.

added page reload for put call

---

public/js/stats.js
views/stats.handlebars

- Removed user personal stats chart (will replace if we end up doing  a login system)
- Removed handlebar code that wasn't doing anything -- I don't believe handlebars will work with the chart in general but I will pursue after we get other functionalities live on the site

Adjusted stats page

---

public/js/logIn.js
routes/navigation-routes.js
routes/users-api-routes.js
views/logIn.handlebars

Basic validation works for login by checking username input against Users table. 
**TO DO's:**
- Update User model w/ password column
- Update seed data with password data
- Update validation to include password check
- Pass user data to dashboard view to display only task/project data for the user

Basic validation for login page

---

models/users.js
seed.js

Added password column in User model and password data to seeds.

Updated model with password column and seeds with passwords

---

public/js/dashboard.js
routes/tasks-routes.js

Delete from dashboard

---

public/assets/css/style.css
public/js/project.js
views/project.handlebars

in project page
double click on project description to edit
click outside of textarea to finish editing
new text remains in same html element with the same project id in data-attr

able to edit project desc

---

public/js/logIn.js

Password validation should work now from login page

---

public/js/dashboard.js
public/js/logIn.js
routes/navigation-routes.js
views/dashboard.handlebars

- updated the log in so that we're storing username in a cookie so data persists between requests
- just have it returning hard coded object for myTasks right now (STILL NEED TO WRITE THE db.find for this query)
- removed unnecessary functions from the dashboard.js file since we're correctly rendering the information via handlebars now

More tests

---

views/dashboard.handlebars

this should fix the view projects and tasks issue

updated href path

---

public/js/viewTask.js
views/task.handlebars

Title is now editable from View Task page

Task title is now editable

---

public/js/dashboard.js
routes/navigation-routes.js
views/dashboard.handlebars

Need to get delete functions working still, but this is looking promising

"my tasks" working on dashboard

---

public/js/signUp.js
routes/navigation-routes.js
views/signUp.handlebars

now able to create a new account and then log in as the new user

Add sign up

---

public/js/project.js
routes/projects-routes.js

fixed description text bug when toggling between edit and save

fix display toggle bug

---

public/js/dashboard.js
views/dashboard.handlebars

Delete my tasks functions work on Dashboard

---

public/js/project.js
routes/projects-routes.js
views/logIn.handlebars

Login layout

---

public/js/viewTask.js
views/newTask.handlebars
views/task.handlebars

Appropriate team member options are now rendering inside of the drop down.  The user id is accessible through the data-assigneeId attribute.

Update task assignee

---

public/js/viewTask.js
views/task.handlebars

If task's associated project is not assigned a team an error message will appear

If task's associated project is not assigned a team

---

public/js/viewTask.js
routes/tasks-routes.js
views/task.handlebars

fix task description edit bug
bring toggle button to task
show/hide textarea for user to edit/save new description.
revise task get api route

Task page update

---

public/js/viewTask.js
views/task.handlebars

Update employee PUT request complete. Strange bug inside of both the update status and update assignee. Appears to be skipping over the location.reload

Update assignee PUT statement complete

---

public/js/stats.js
views/dashboard.handlebars
views/stats.handlebars

Rendering user task data into a chart

User task chart

---

config/config.json

I think this should get jawsDB setup from the config file.

Setting up jawsDB

---

Procfile

I believe adding this Procfile will resolve the issue.

Fix for Heroku server crashing

---

routes/navigation-routes.js

Added a navigation path to hopefully resolve issues with heroku deployment

Still trying to fix issue with heroku deployment

---

Procfile
routes/navigation-routes.js

Removed last two recent changes!

fixed recent changes

---

server.js

Added if block to render jawsDB in server.js

---

routes/tasks-routes.js

Fixed rendering bug

---

models/index.js
server.js

Updated index file to route to production and removed "if" statement in server file.

fixing heroku deployment

---

public/assets/css/style.css
views/dashboard.handlebars
views/layouts/main.handlebars
views/logIn.handlebars

Polished sign in page as well as dashboard a bit

Polishing css

---

models/index.js
models/tasks.js
public/js/newTask.js
routes/tasks-routes.js

changed Status model default status_code value from 0 to 1.
changed sequelize config from 'production' to 'development'.
Closes #127

revert db config to dev, fix default status code in Status model

---

seed.js

fixed seed bug, where a task is assigned to a user without assigning to a project.

fix unassigned project task bug

---

public/js/newTask.js
routes/tasks-routes.js

fixed new task page drop down list user bug.
fixed new task missing team_id bug

new task page fix

---

public/assets/css/style.css
public/js/newProject.js
views/project.handlebars

got the routes working correctly once user clicks submit new project

Style view task and project 

---

public/assets/css/style.css
views/dashboard.handlebars
views/signUp.handlebars
views/stats.handlebars

There were some overflow:hidden issues so I adjusted margins to ensure full boxes were showing and it retained mobile-friendly responsiveness.

Quick img fix

---

public/assets/css/style.css
views/newTask.handlebars

Fixed styling
